# Generated by Django 4.0.3 on 2023-02-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(max_length=10)),
                ('club_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('stu_id', models.IntegerField()),
                ('club_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('task', models.TextField(default='No task')),
                ('status', models.CharField(default='in progress', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('cgpa', models.FloatField(max_length=100)),
                ('dept_name', models.CharField(max_length=100)),
                ('year', models.IntegerField(max_length=1)),
                ('pic', models.ImageField(blank=True, default='profile.png', null=True, upload_to='media')),
            ],
        ),
    ]
