# Generated by Django 4.0.3 on 2023-02-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_remove_clubs_id_alter_clubs_club_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='stu_id',
        ),
        migrations.AddField(
            model_name='events',
            name='poster',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to='media'),
        ),
    ]
