# Generated by Django 4.0.3 on 2023-02-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_remove_events_stu_id_events_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('stu_id', models.IntegerField()),
            ],
        ),
    ]
