# Generated by Django 4.0.3 on 2023-03-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_event_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_members',
            name='position',
            field=models.CharField(default='Executive member', max_length=20),
        ),
    ]
