# Generated by Django 4.0.3 on 2023-03-14 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_club_members_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.CharField(default='5:00 pm-6:00 pm', max_length=20),
        ),
    ]
