# Generated by Django 4.0.3 on 2023-03-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_alter_events_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='poster',
            field=models.ImageField(blank=True, default='events.jpeg', null=True, upload_to='media'),
        ),
    ]
