# Generated by Django 4.0.3 on 2023-04-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0012_alter_events_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='club_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
