# Generated by Django 4.0.3 on 2023-04-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0014_events_pics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events_pics',
            name='event_id',
        ),
        migrations.AddField(
            model_name='events_pics',
            name='event_name',
            field=models.CharField(default='ptm100', max_length=100),
            preserve_default=False,
        ),
    ]
